### ISSUE TITLE
Collaborate with the Kibana Team

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/monorepo-test#14]
> [<img alt="daedalus28" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/daedalus28) **Authored by [daedalus28](https://github.com/daedalus28)**
_<time datetime="2018-03-02T19:13:54Z" title="Friday, March 2nd 2018, 2:13:54 pm -05:00">Mar 2, 2018</time>_

---

This issue is to start the discussion on how kibana and contexture can collaborate better and make both of our jobs easier 😄 

This repo is the DSL processor and includes links to our other relevant repos. Our react components are still a work in progress but you can expect rapid progress on them. In particular, a good place to start is probably the talk I just gave about contexture: https://github.com/smartprocure/contexture-ec18-talk. At the top of that repo is a link to a youtube video of the talk.

Forgive the spam, but I figured this was the best way to ping the people I spoke with at Elasticon. If you can all ping any of the relevant people I missed, I'd really appreciate it.

@spalger
@cjcenizal
@lukasolson
@w33ble
@Bargs
@chrisronline

**Comment by cjcenizal** [comment]
@stellarhoof I think the only active Elastician on that list is Lukas (I left Elastic in September).

**Comment by stellarhoof** [comment]
Hahaha @cjcenizal thanks for the comment and apologies for the noise. You got pinged because we're looking to migrate issues from one repo to another and I guess GH pings when a new issue is created. Good to keep in mind :)

**Comment by daedalus28** [comment]
Thanks for responding here - I'm closing this to avoid further spam 😓
